syntax = "proto3";

package grid;

option go_package = "grid.v3;gridv3";

service ClientService {
  rpc AddTask(TaskTaxiPassenger) returns (TaskRequest);
  rpc GetTaskResult(TaskRequest) returns (TaskResult);
}

service DispatcherService {
  rpc GetTask(TaskRequest) returns (Task);
  rpc SubscribeTasks(SubscribeRequest) returns (stream TaskRequest);
  rpc GetSubTask(stream TaskRequest) returns (stream SubTask);
  rpc SubmitResult(SubTaskResult) returns (Ack);
}

message SubscribeRequest {}

message TaskTaxiPassenger {
  Graph graph = 1;
  repeated int32 taxi_nodes = 2;
  repeated int32 passenger_nodes = 3;
  repeated int32 destination_nodes = 4;
}

message Graph {
  int32 nodes = 1;
  repeated Edge edges = 2;
}

message Edge {
  int32 from = 1;
  int32 to = 2;
  int32 weight = 3;
}

message TaskRequest {
  int64 task_id = 1;
}

message Task {
  int64 id = 1;

  bytes jsonBase = 2;
  bytes binary = 3;
}

message SubTask {
  int64 id = 1;
  int64 task_id = 2;

  bytes jsonSubTask = 3;
}

message SubTaskResult {
  int64 id = 1;
  int64 task_id = 2;

  bytes jsonSubTask = 3;
}

message Ack {
  bool ok = 1;
}

message TaskResult {
  int64 task_id = 1;
  oneof status {
    TaskPending pending = 2;
    TaskCompleted completed = 3;
    TaskFailed failed = 4;
  }
}

message TaskPending {
  int32 total_subtasks = 1;
  int32 completed_subtasks = 2;
  string message = 3;
}

message TaskCompleted {
  int64 best_cost = 1;
  repeated Assignment assignments = 2;
  int64 processed_permutations = 3;
}

message TaskFailed {
  string error = 1;
}

message Assignment {
  int32 taxi_node = 1;
  int32 passenger_node = 2;
  int32 destination_node = 3;
  int64 cost = 4;
}